name: "Adicionar reviewers automaticamente"

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar revisores automaticamente
        uses: necojackarc/auto-request-review@v0.6.0
        with:
          config: .github/reviewers.yml
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}