name: "Adicionar Reviewers automaticamente"

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar reviewers automaticamente
        uses: ahmadnassri/action-auto-request-review@v1
        with:
          reviewers: ilidiomagalhaes,hugocoelho-isep,pauloabreu13,pedrojoiliveira
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}